apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: counter-backend:1
        env:
        - name: DB_HOST
          value: postgres
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: nikokirilenko
        - name: DB_PASSWORD
          value: pass1234
        - name: DB_NAME
          value: counter
        ports:
        - containerPort: 8000